install.packages("e1071")
install.packages("EnvStats")
install.packages("car", dependencies = TRUE)
install.packages("agricolae")
install.packages("FSA")
install.packages("schoolmath")
install.packages("UsingR")
install.packages("PBImisc")
install.packages("multcomp")
install.packages("ROCR")
install.packages("ape")
install.packages("vegan")
install.packages("MASS")

library(e1071)
library(EnvStats)
library(car)
library(agricolae)
library(FSA)
library(schoolmath)
library(UsingR)
library(PBImisc)
library(multcomp)
library(ROCR)
library(ape)
library(vegan)
library(MASS)